baseURL = "barkouch.me"
languageCode = "en-us"
title = "Smail Barkouch"
theme = "PaperMod"
paginate = 5

[params]
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false

[params.profileMode]
enabled = true
title = "Smail Barkouch"
subtitle = "CS student @ **Rutgers University**, and founding software engineer at **[Lockbook](https://lockbook.net)**."
imageUrl = "img/profile.png"
imageTitle = "smail's picture"
imageWidth = 150
imageHeight = 150

[[params.socialIcons]]
name = "github"
url = "https://github.com/smailbarkouch"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/smailbarkouch"

[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/user/noqs1jnz7jvjr13ycyg154qqh?si=0663cbabfc8c49ca"

[[params.socialIcons]]
name = "email"
url = "mailto:smail@barkouch.me"

[menu]
[[menu.main]]
identifier = 'about'
name = 'About'
pageRef = '/about'
weight = 1

[[menu.main]]
identifier = 'blog'
name = 'Blog'
pageRef = '/blog/'
weight = 4

[[menu.main]]
identifier = 'resume'
name = 'Resume'
url = "https://drive.google.com/file/d/1n0PAURcfm94rL_opW0QIgQjiN9ZQcVde/view?usp=sharing"
weight = 5
