baseURL = "barkouch.me"
languageCode = "en-us"
title = "Smail Barkouch"
theme = "typo"

[params]
homeIntroTitle = "Hi! 👋"
homeIntroContent = """
I'm Smail. I'm graduating from [Rutgers University](https://www.rutgers.edu/new-brunswick) this December and currently work as a Founding Software Engineer at [Lockbook](https://lockbook.net), a private, secure, [open-source](https://github.com/lockbook/lockbook) note-taking platform.
"""
homeCollectionTitle = 'Blog'
homeCollection = 'blog'
paginationSize = 100

[[params.social]]
name = "github"
url = "https://github.com/smailbarkouch"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/smailbarkouch"

[[params.social]]
name = "spotify"
url = "https://open.spotify.com/user/noqs1jnz7jvjr13ycyg154qqh?si=0663cbabfc8c49ca"

[[params.social]]
name = "email"
url = "mailto:smail@barkouch.me"

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "resume"
url = "https://drive.google.com/file/d/1n0PAURcfm94rL_opW0QIgQjiN9ZQcVde/view?usp=sharing"
